# Generated by Django 3.2 on 2021-05-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Porduct',
        ),
    ]
