# Generated by Django 3.2 on 2021-05-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0003_porduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='porduct',
            name='Picture',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
