# Generated by Django 3.2 on 2021-05-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0004_porduct_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Porduct',
            new_name='Product',
        ),
    ]
