# Generated by Django 3.2 on 2021-05-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0005_rename_porduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Sizes',
            field=models.CharField(choices=[('1', '22'), ('2', '24'), ('3', '26'), ('4', '28'), ('5', '30'), ('6', '32'), ('7', '34')], default='', max_length=300),
            preserve_default=False,
        ),
    ]
