# Generated by Django 3.2 on 2021-05-03 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0006_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Sizes',
        ),
        migrations.CreateModel(
            name='Size_Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField()),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.product')),
            ],
        ),
    ]
