# Generated by Django 3.2 on 2021-05-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0007_auto_20210503_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size_choices',
            name='choice',
            field=models.CharField(max_length=100),
        ),
    ]
