# Generated by Django 3.2 on 2021-05-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0008_alter_size_choices_choice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Size_Choices',
            new_name='Size_Choice',
        ),
    ]
