# Generated by Django 3.2 on 2021-05-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0009_rename_size_choices_size_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='choices',
            field=models.JSONField(blank=True, default=''),
        ),
    ]
