# Generated by Django 3.2 on 2021-05-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0010_product_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='choices',
        ),
        migrations.AddField(
            model_name='product',
            name='Choices',
            field=models.JSONField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
