# Generated by Django 3.2 on 2021-05-04 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0011_auto_20210504_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Choices',
        ),
    ]
