# Generated by Django 3.2 on 2021-05-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0013_product_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Stock',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
