# Generated by Django 3.2 on 2021-05-04 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0015_alter_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Stock',
        ),
    ]
