# Generated by Django 3.2 on 2021-05-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0020_auto_20210505_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='User',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='Wish_List',
            field=models.JSONField(blank=True, default=''),
        ),
    ]
