# Generated by Django 3.2 on 2021-05-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0022_auto_20210505_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=20)),
                ('Cart', models.JSONField()),
                ('Wish_List', models.JSONField(blank=True, default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
