# Generated by Django 3.2 on 2021-05-05 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0023_auto_20210505_2159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='UserDetails',
        ),
    ]
