# Generated by Django 3.2 on 2021-05-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0024_rename_cart_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='Picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='Choices',
            field=models.JSONField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='size_choice',
            name='choice',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='Cart',
            field=models.JSONField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='Wish_List',
            field=models.JSONField(blank=True, default=0),
        ),
    ]
