# Generated by Django 3.2 on 2021-05-10 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0026_auto_20210510_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='photo',
            new_name='Picture',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='url',
            new_name='Url',
        ),
    ]
