# Generated by Django 3.2 on 2021-05-10 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0027_auto_20210510_1152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
