# Generated by Django 3.2 on 2021-05-10 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0029_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
