# Generated by Django 3.2 on 2021-05-10 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0031_userprfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPrfile',
            new_name='UserProfile',
        ),
    ]
