# Generated by Django 3.2 on 2021-05-10 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0032_rename_userprfile_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
