# Generated by Django 3.2 on 2021-05-10 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0034_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='UserProfile',
        ),
    ]
