# Generated by Django 3.2 on 2021-05-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0036_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemQty', models.IntegerField()),
                ('Email', models.CharField(max_length=100)),
                ('PhoneNumber', models.IntegerField()),
                ('Address', models.TextField()),
                ('Address2', models.TextField(blank=True)),
                ('Province', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=100)),
                ('ZipPortal', models.IntegerField()),
                ('Details_On_Email', models.BooleanField()),
            ],
        ),
    ]
