# Generated by Django 3.2 on 2021-05-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0039_rename_orders_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ItemPrice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
