# Generated by Django 3.2 on 2021-05-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0040_order_itemprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ItemPrice',
        ),
    ]
