# Generated by Django 3.2 on 2021-05-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0041_remove_order_itemprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ItemPrice',
            field=models.IntegerField(default=1),
        ),
    ]
