# Generated by Django 3.2 on 2021-05-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0042_order_itemprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Picture1',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='Picture2',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
