# Generated by Django 3.2 on 2021-05-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0043_auto_20210513_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Picture1',
            new_name='Picture3',
        ),
    ]
