# Generated by Django 3.2 on 2021-05-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0044_rename_picture1_product_picture3'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Picture4',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
