# Generated by Django 3.2 on 2021-05-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0045_product_picture4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intresting_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=20)),
                ('Product', models.IntegerField()),
            ],
        ),
    ]
