# Generated by Django 3.2 on 2021-05-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0046_intresting_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Intresting_Products',
            new_name='Intresting_Product',
        ),
    ]
