# Generated by Django 3.2 on 2021-05-19 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0047_rename_intresting_products_intresting_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Pub_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
